services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your-secret-key
      - ADMIN_PASSWORD=admin123
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev:full 
